name: Build wheels

on:
  push:
    branches: ["all-gha"]
  workflow_dispatch:

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.1
        env:
          # Build for CPython 3.11 and 3.12
          CIBW_BUILD: cp311-* cp312-*

          ## -------------------
          ## Linux setup
          ## -------------------
          CIBW_BEFORE_BUILD_LINUX: |
            yum install -y epel-release
            yum install -y armadillo-devel lapack-devel blas-devel cmake ninja-build pkgconfig
          CIBW_ENVIRONMENT_LINUX: >
            PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig

          ## -------------------
          ## macOS setup (Apple Silicon)
          ## -------------------
          CIBW_BEFORE_BUILD_MACOS: |
            brew update || true
            brew install armadillo
          CIBW_ENVIRONMENT_MACOS: >
            PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/usr/local/lib/pkgconfig

          ## -------------------
          ## Shared setup
          ## -------------------
          CIBW_BEFORE_BUILD: |
            pip install meson-python pybind11 ninja meson

          CIBW_TEST_REQUIRES: numpy scipy pytest
          CIBW_TEST_COMMAND: pytest {project}/tests
