name: Build wheels

on:
  push:
    branches: ["all-gha"]
  workflow_dispatch:

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.1
        env:
          # Build for CPython 3.11 and 3.12
          CIBW_BUILD: cp311-* cp312-*

          ## -------------------
          ## Windows setup
          ## -------------------

          CIBW_BEFORE_BUILD_WINDOWS: |
            curl -L -o micromamba.exe https://micro.mamba.pm/api/micromamba/win-64/latest
            mkdir C:\micromamba
            move micromamba.exe C:\micromamba\
            C:\micromamba\micromamba.exe create -y -p C:\buildenv -c conda-forge armadillo
            echo CIBW_CPPFLAGS=C:\buildenv\Library\include>> %GITHUB_ENV%
            echo CIBW_LDFLAGS=C:\buildenv\Library\lib -larmadillo>> %GITHUB_ENV%
            echo PATH=C:\buildenv\Library\bin;%PATH%>> %GITHUB_ENV%

          CIBW_ENVIRONMENT_WINDOWS: >
            PATH=C:\buildenv\Library\bin;$PATH

          ## -------------------
          ## Shared setup
          ## -------------------
          CIBW_BEFORE_BUILD: |
            pip install meson-python pybind11 ninja meson

          CIBW_TEST_REQUIRES: numpy scipy pytest
          CIBW_TEST_COMMAND: pytest {project}/tests
